# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Deploy

on:
  push:
    branches: ["main"]

  pull_request:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            export PATH=$PATH:/usr/local/go/bin
            cd miniProject
            git pull
            sudo docker build -t go-miniproject-devangga .
            sudo docker stop go-miniproject-devangga
            sudo docker rm go-miniproject-devangga
            sudo docker run -d --name go-miniproject-devangga -dp 8081:8080 go-miniproject-devangga
